USE lab
GO
START TRANSACTION;
WITH DELETEDOUBLE 
AS (
	SELECT ROW_NUMBER() OVER(PARTITION BY Names ORDER BY Names) NamesN, Families
	FROM PersonT
)
DELETE
FROM DELETEDOUBLE
WHERE NamesN > 1
ROLLBACK;